module.exports = {
  asNum: require("./as-num"),
  attributeSorter: require("./attribute-sorter"),
  codeLetters: require("./code-letters"),
  collectColours: require("./collect-colours"),
  colours: require("./colours"),
  constants: require("./constants"),
  drawLine: require("./draw-line"),
  emptyData: require("./empty-data"),
  fillCircle: require("./fill-circle"),
  fillDirection: require("./fill-direction"),
  fillRect: require("./fill-rect"),
  loadImg: require("./load-img"),
  partialRotate: require("./partial-rotate"),
  quadrantZoom: require("./quadrant-zoom"),
  random: require("./random"),
  rotations: require("./rotations"),
  setImg: require("./set-img"),
  wrapPosition: require("./wrap-position"),
  zoomIn: require("./zoom-in")
};
